# whether kernel is < 4.1 or not
old_kernel = false

capture_size_limit = 4096

# in nano seconds, 1 milliseconds
control_command_receive_timeout = 1_000_000
# in nano seconds, 0.5 milliseconds
capture_thread_receive_timeout = 500_000

cpu_to_capture = "1-1024"

# cpu string to capture, this only affect task dead event, but need to be larger than total cpu so thing works correctly
# the string also need to be smaller than 32 characters
# time interval to publish message to kafka (in seconds)
publish_msg_interval = 10

# if false, send data to kafka, otherwise write to json
dev_flag = false

# the list of containers and pid to monitor, each section is an entry to containerList
# / namespace is the root namespace
[[monitor_targets]]
container_name = "/"
pid_list = [1]

#################################### Filter options ####################################
[filter]
unix_timestamp = true
[filter.network_rawstat]
[filter.network_rawstat.interface_rawstat]
iname = true
description = true
uni_connection_stats = true

[filter.process]
pid = true
parent_pid = true
uid = true
effective_uid = true
saved_uid = true
fs_uid = true
gid = true
effective_gid = true
saved_gid = true
fs_gid = true
real_pid = true
real_parent_pid = true
real_uid = true
real_effective_uid = true
real_saved_uid = true
real_fs_uid = true
real_gid = true
real_effective_gid = true
real_saved_gid = true
real_fs_gid = true
exec_path = true
command = true
child_real_pid_list = true

[filter.process.stat]
timestamp = true
total_system_cpu_time = true
total_user_cpu_time = true
total_cpu_time = true
total_rss = true
total_vss = true
total_swap = true
total_io_read = true
total_io_write = true
total_block_io_read = true
total_block_io_write = true

[filter.process.stat.netstat]
pack_sent = true
pack_recv = true
total_data_sent = true
total_data_recv = true
real_data_sent = true
real_data_recv = true

[filter.process.stat.netstat.interface_stat]
iname = true
packet_sent = true
packet_recv = true
total_data_sent = true
total_data_recv = true
real_data_sent = true
real_data_recv = true
connection_stats = true

[[filter.process.threads]]
tid = true
pid = true
real_tid = true
real_pid = true

[filter.process.threads.stat]
timestamp = true
total_system_cpu_time = true
total_user_cpu_time = true
total_cpu_time = true
total_io_read = true
total_io_write = true
total_block_io_read = true
total_block_io_write = true
