name="VS1"
cluster="C1"

capture_size_limit = 4096
capture_thread_receive_timeout = 500000
control_command_receive_timeout = 1000000
cpu_to_capture = "1-1024"
dev_flag = true
old_kernel = false
publish_msg_interval = 2
# msg_chunk_size = 2048

[[monitor_targets]]
container_name = "/"
pid_list = [1]

[filter]
unix_timestamp = true
[filter.network_rawstat.interface_rawstat]
description = true
iname = true
uni_connection_stats = true

[filter.process]
child_real_pid_list = true
command = true
effective_gid = true
effective_uid = true
exec_path = true
fs_gid = false
fs_uid = true
gid = true
parent_pid = true
pid = true
real_effective_gid = false
real_effective_uid = false
real_fs_gid = false
real_fs_uid = false
real_gid = false
real_parent_pid = false
real_pid = false
real_saved_gid = false
real_saved_uid = false
real_uid = false
saved_gid = false
saved_uid = true
uid = true

[filter.process.stat]
timestamp = true
total_block_io_read = true
total_block_io_write = true
total_cpu_time = true
total_io_read = true
total_io_write = true
total_rss = true
total_swap = true
total_system_cpu_time = true
total_user_cpu_time = true
total_vss = true

[filter.process.stat.netstat]
pack_recv = true
pack_sent = true
real_data_recv = true
real_data_sent = true
total_data_recv = true
total_data_sent = true

[filter.process.stat.netstat.interface_stat]
connection_stats = true
iname = true
packet_recv = true
packet_sent = true
real_data_recv = true
real_data_sent = true
total_data_recv = true
total_data_sent = true

[filter.process.thread]
pid = true
real_pid = true
real_tid = true
tid = true

[filter.process.thread.stat]
timestamp = true
total_block_io_read = true
total_block_io_write = true
total_cpu_time = true
total_io_read = true
total_io_write = true
total_system_cpu_time = true
total_user_cpu_time = true
